### ISSUE TITLE
[FEATURE] Hide ref_id column from exported spreadsheet

### ISSUE THREAD

**Issue by lorawoodford** [Smithsonian/as_spreadsheet_bulk_updater#1]
**Is your feature request related to a problem? Please describe.**
Ref_ids carry a fair bit of meaning here, so we want to tightly control how they can be minted and updated.  To do so, we have a [plugin](https://github.com/Smithsonian/caas_aspace_refid) that uses established logic to autogenerate new archival object refids, but there are still other means by which users can intentionally or unintentionally create or change refids in non-standard ways.  This bulk update workflow is one of those ways.

**Describe the solution you'd like**
So that untracked ref_ids can't make their way into ASpace via the bulk update workflow, we've opted to hide the ref_id column from the original spreadsheet export (this tracks with the custom templates that we already use for the "Load via Spreadsheet" workflow).

**Describe alternatives you've considered**
See https://github.com/Smithsonian/caas_aspace_refid/issues/15

**Additional context**
In the future, this forked version of the plugin will be unecessary as this functionality is being incorporated into aspace 4.0.  When that is complete, we will roll out a lighter weight plugin that accomplishes the same by hiding the ref_id column as a selectable field for spreadsheet export.

**Comment by lorawoodford** [comment]
@fordmadox , @crugas - I've deployed this to aspace02 and have tested out the functionality and all appears to be in working order.

Prior to updating this plugin, users were presented the option of exporting ref_ids:
![Image](https://github.com/user-attachments/assets/65a0588a-e144-4c1d-a5fc-47960e455ebc)

After updating the plugin, this check box is now gone:
![Image](https://github.com/user-attachments/assets/b69cc2e0-cc50-4daa-9fbe-35f02175ffb9)

And the resulting spreadsheet exports are as expected (top spreadsheet from before plugin update/includes refid, bottom spreadsheet from after plugin update/excludes refid):
![Image](https://github.com/user-attachments/assets/01d7d609-514e-4a45-b973-35ce7c1a449f)

I also confirmed that making a few modifications in the new/post-plugin-update spreadsheet and running the bulk update job performed as expected.  Two "repository processing notes" were added to the Garden of Eden collection without issue. See: https://aspacetest.si.edu/resources/53849#tree::archival_object_6126170 and https://aspacetest.si.edu/resources/53849#tree::archival_object_6126194

**Comment by crugas** [comment]
Looks fantastic @lorawoodford !
